include: package:lints/recommended.yaml

linter:
  rules:
    - public_member_api_docs
    - sort_constructors_first
    - prefer_single_quotes
    - unawaited_futures
    - avoid_redundant_argument_values