name: cldf
description: A Dart implementation of the Crushlog Data Format (CLDF) for climbing data exchange.
version: 1.2.0
homepage: https://github.com/petrmac/crushlog-data-format-spec
repository: https://github.com/petrmac/crushlog-data-format-spec/tree/main/clients/dart/cldf
issue_tracker: https://github.com/petrmac/crushlog-data-format-spec/issues

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  archive: ^4.0.7
  crypto: ^3.0.3
  json_annotation: ^4.9.0
  collection: ^1.18.0
  meta: ^1.11.0
  intl: ^0.20.2

dev_dependencies:
  build_runner: ^2.4.0
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.24.0
  path: ^1.9.0