name: Dart Release

on:
  push:
    tags:
      - 'dart-v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.3.2)'
        required: true
        type: string
      dry_run:
        description: 'Dry run (skip actual publishing)'
        required: false
        type: boolean
        default: false

jobs:
  validate-and-test:
    name: Validate and Test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    defaults:
      run:
        working-directory: clients/dart/cldf
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Determine version
      id: version
      run: |
        if [[ "${{ github.event_name }}" == "push" ]]; then
          VERSION=${GITHUB_REF#refs/tags/dart-v}
        else
          VERSION=${{ github.event.inputs.version }}
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
        
    - name: Install dependencies
      run: dart pub get
      
    - name: Run tests
      run: dart test
      
    - name: Check formatting
      run: dart format --set-exit-if-changed .
      
    - name: Analyze code
      run: dart analyze --fatal-infos

  publish:
    name: Publish to pub.dev
    needs: validate-and-test
    runs-on: ubuntu-latest
    if: github.event.inputs.dry_run != 'true'
    environment:
      name: pub.dev
      url: https://pub.dev/packages/cldf
    defaults:
      run:
        working-directory: clients/dart/cldf
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
        
    - name: Update version in pubspec.yaml
      run: |
        sed -i "s/^version: .*/version: ${{ needs.validate-and-test.outputs.version }}/" pubspec.yaml
        
    - name: Install dependencies
      run: dart pub get
      
    - name: Setup pub credentials
      run: |
        mkdir -p ~/.pub-cache
        echo '${{ secrets.PUB_CREDENTIALS }}' > ~/.pub-cache/credentials.json
        
    - name: Publish to pub.dev
      run: dart pub publish --force
      
    - name: Verify publication
      run: |
        sleep 10  # Give pub.dev time to update
        dart pub global activate cldf
        dart pub global run cldf --version

  create-release:
    name: Create GitHub Release
    needs: [validate-and-test, publish]
    runs-on: ubuntu-latest
    if: github.event.inputs.dry_run != 'true'
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Generate Release Notes
      id: release_notes
      run: |
        VERSION=${{ needs.validate-and-test.outputs.version }}
        cat > release-notes.md << EOF
        # Dart Client v${VERSION}
        
        ## Installation
        
        Add to your \`pubspec.yaml\`:
        \`\`\`yaml
        dependencies:
          cldf: ^${VERSION}
        \`\`\`
        
        Then run:
        \`\`\`bash
        dart pub get
        \`\`\`
        
        ## What's Changed
        See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/clients/dart/cldf/CHANGELOG.md) for details.
        
        ## pub.dev
        View package at https://pub.dev/packages/cldf
        EOF
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: dart-v${{ needs.validate-and-test.outputs.version }}
        name: Dart Client v${{ needs.validate-and-test.outputs.version }}
        body_path: release-notes.md
        draft: false
        prerelease: false