name: SonarCloud Analysis

on:
  workflow_run:
    workflows: ["Java CI", "Dart CI"]
    types:
      - completed
    branches: [ main, develop ]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'push' && 
      github.event.workflow_run.conclusion == 'success'
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones should be disabled for better analysis
    
    # Download Java coverage artifacts
    - name: Download Java coverage
      uses: actions/github-script@v7
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
             owner: context.repo.owner,
             repo: context.repo.repo,
             run_id: context.payload.workflow_run.id,
          });
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "java-coverage-reports"
          })[0];
          if (matchArtifact) {
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/java-coverage.zip`, Buffer.from(download.data));
          } else {
            console.log('No Java coverage artifact found');
          }
    
    - name: Extract Java coverage
      run: |
        if [ -f java-coverage.zip ]; then
          unzip -o java-coverage.zip -d clients/java/
          echo "Java coverage extracted"
        else
          echo "No Java coverage to extract"
        fi
    
    # Download Dart coverage artifacts
    - name: Download Dart coverage
      uses: actions/github-script@v7
      with:
        script: |
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
             owner: context.repo.owner,
             repo: context.repo.repo,
             run_id: context.payload.workflow_run.id,
          });
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "dart-test-reports"
          })[0];
          if (matchArtifact) {
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/dart-coverage.zip`, Buffer.from(download.data));
          } else {
            console.log('No Dart coverage artifact found');
          }
    
    - name: Extract Dart coverage
      run: |
        if [ -f dart-coverage.zip ]; then
          mkdir -p temp-dart-coverage
          unzip -o dart-coverage.zip -d temp-dart-coverage/
          echo "Dart coverage extracted to temp directory"
          ls -la temp-dart-coverage/
          
          # Move lcov.info to the expected location
          mkdir -p clients/dart/cldf/coverage
          if [ -f temp-dart-coverage/lcov.info ]; then
            cp temp-dart-coverage/lcov.info clients/dart/cldf/coverage/
            echo "Moved lcov.info to clients/dart/cldf/coverage/"
          elif [ -f temp-dart-coverage/coverage/lcov.info ]; then
            cp temp-dart-coverage/coverage/lcov.info clients/dart/cldf/coverage/
            echo "Moved coverage/lcov.info to clients/dart/cldf/coverage/"
          fi
          
          # Note: test-results.xml is optional and not required for SonarCloud
          
          if [ -f clients/dart/cldf/coverage/lcov.info ]; then
            echo "lcov.info successfully placed, first 10 lines:"
            head -10 clients/dart/cldf/coverage/lcov.info
            echo "Total lines in lcov.info:"
            wc -l clients/dart/cldf/coverage/lcov.info
            
            # Fix paths to be relative for SonarCloud
            echo "Fixing paths in lcov.info for SonarCloud..."
            cp clients/dart/cldf/coverage/lcov.info clients/dart/cldf/coverage/lcov.info.original
            sed "s|SF:.*/lib/|SF:lib/|g" clients/dart/cldf/coverage/lcov.info.original > clients/dart/cldf/coverage/lcov.info
            echo "Paths fixed. Sample paths after fixing:"
            grep "^SF:" clients/dart/cldf/coverage/lcov.info | head -5
          else
            echo "ERROR: lcov.info not found after extraction"
          fi
        else
          echo "No Dart coverage to extract"
        fi
    
    # Java Setup for SonarCloud scanner
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Cache SonarQube packages
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    # Build Java project to generate binaries needed for analysis
    - name: Build Java project
      working-directory: clients/java
      run: |
        chmod +x gradlew
        mkdir -p cldf-java/src/main/resources
        rm -rf cldf-java/src/main/resources/schemas
        cp -r ../../schemas cldf-java/src/main/resources/
        ./gradlew build -x test
    
    # Run SonarCloud analysis using Gradle for Java only first
    - name: Run SonarCloud Analysis for Java
      working-directory: clients/java
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        ./gradlew sonar \
          -Dsonar.projectKey=petrmac_crushlog-data-format-spec \
          -Dsonar.organization=petrmacek \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.projectName="CrushLog Data Format - Java" \
          -Dsonar.projectVersion=1.1.1 \
          --info
    
    # Debug: Check coverage file before Sonar analysis
    - name: Verify Dart coverage before SonarCloud
      run: |
        echo "Checking for coverage file..."
        if [ -f clients/dart/cldf/coverage/lcov.info ]; then
          echo "✓ Coverage file exists at clients/dart/cldf/coverage/lcov.info"
          echo "File size: $(ls -lh clients/dart/cldf/coverage/lcov.info | awk '{print $5}')"
          echo "Line count: $(wc -l clients/dart/cldf/coverage/lcov.info | awk '{print $1}')"
          echo "First few SF entries (source files):"
          grep "^SF:" clients/dart/cldf/coverage/lcov.info | head -5
          echo "Coverage summary (files with coverage > 0):"
          awk '/^SF:/ {file=$0} /^LH:/ {if ($2 > 0) print file " - Lines Hit: " $2}' clients/dart/cldf/coverage/lcov.info | head -10
        else
          echo "✗ Coverage file NOT found at clients/dart/cldf/coverage/lcov.info"
          echo "Contents of clients/dart/cldf/:"
          ls -la clients/dart/cldf/ || echo "Directory not found"
          echo "Contents of clients/dart/cldf/coverage/:"
          ls -la clients/dart/cldf/coverage/ || echo "Directory not found"
        fi
    
    # Setup Dart for dependency resolution
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    
    - name: Install Dart dependencies
      working-directory: clients/dart/cldf
      run: |
        dart pub get
        dart run build_runner build --delete-conflicting-outputs
    
    - name: Extract version from pubspec
      id: dart_version
      working-directory: clients/dart/cldf
      run: |
        VERSION=$(grep "^version:" pubspec.yaml | cut -d' ' -f2)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Dart package version: $VERSION"
    
    - name: Final coverage check before SonarCloud
      working-directory: clients/dart/cldf
      run: |
        if [ -f coverage/lcov.info ]; then
          echo "✓ Final coverage file check:"
          echo "  File size: $(ls -lh coverage/lcov.info | awk '{print $5}')"
          echo "  Line count: $(wc -l coverage/lcov.info | awk '{print $1}')"
          echo "  Sample paths (should be relative like 'lib/...'):"
          grep "^SF:" coverage/lcov.info | head -3
          echo "  Files with coverage:"
          grep "^SF:" coverage/lcov.info | wc -l
          echo "  Absolute path check:"
          echo "  PWD: $(pwd)"
          echo "  Coverage file absolute path: $(realpath coverage/lcov.info)"
        else
          echo "✗ ERROR: coverage/lcov.info not found!"
          echo "  PWD: $(pwd)"
          echo "  Directory contents:"
          ls -la
          echo "  Coverage directory contents:"
          ls -la coverage/ || echo "Coverage directory not found"
        fi
    
    # Run separate analysis for Dart using the new SonarQube scan action
    - name: Analyze Dart with SonarCloud
      uses: SonarSource/sonarqube-scan-action@v5.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io
      with:
        projectBaseDir: clients/dart/cldf
        args: >
          -Dsonar.projectKey=petrmac_crushlog-data-format-spec-dart
          -Dsonar.organization=petrmacek
          -Dsonar.projectName="CrushLog Data Format - Dart Client"
          -Dsonar.projectVersion=${{ steps.dart_version.outputs.VERSION }}
          -Dsonar.sources=lib
          -Dsonar.tests=test
          -Dsonar.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart,**/generated/**,example/**
          -Dsonar.test.exclusions=**/*_test.dart
          -Dsonar.language=dart
          -Dsonar.coverage.exclusions=**/*.g.dart,**/*.freezed.dart,**/*.mocks.dart
          -Dsonar.dart.lcov.reportPaths=coverage/lcov.info
          -Dsonar.verbose=true
          -Dsonar.links.homepage=https://github.com/petrmac/crushlog-data-format-spec
          -Dsonar.links.ci=https://github.com/petrmac/crushlog-data-format-spec/actions
          -Dsonar.links.scm=https://github.com/petrmac/crushlog-data-format-spec
          -Dsonar.links.issue=https://github.com/petrmac/crushlog-data-format-spec/issues